name: Test Suite

on:
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    phpunit:
        uses: content-pilot/github-actions/.github/workflows/php-unit-tests.yml@1.10.1
        secrets:
            CONTENT_PILOT_USER_TOKEN: ${{ secrets.CONTENT_PILOT_USER_TOKEN }}
